<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-11-11T22:26:57+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'timezone' => 'America/Edmonton',
);
