<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-11-07T19:25:58+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.favicon_fid
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Panoptic Automation',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1446875021,
        'favicon_fid' => '17',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '2',
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
