<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-11-16T21:09:17-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Panoptic Automation',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1446875021,
        'favicon_fid' => '17',
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.2',
        'user_timezones' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '2',
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 0,
    ),
    'maintenance' => array(
        'version_job_page_num' => '192',
    ),
);
